# Redis configuration file example

daemonize no
# logfile ""
# dir /data

bind 0.0.0.0
protected-mode no
port 6379

# Memory management
maxmemory 800mb
maxmemory-policy allkeys-lru

# Persistence
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000